# Generated by Django 4.1.2 on 2022-10-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('breed', models.CharField(default='breed', max_length=200)),
                ('adoptionYear', models.IntegerField(default='2022')),
                ('color', models.CharField(default='color', max_length=200)),
                ('description', models.CharField(default='Good boy', max_length=200)),
            ],
        ),
    ]
